# -*- coding: utf-8 -*-
"""Sales Forecasting Analysis System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DgzzUKOW15Wm5QNueSkdkZ765byRmTqw

Import Libraries
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""Load Dataset"""

df = pd.read_csv("/content/train.csv")

"""Display First 5 Rows"""

print(df.head())

"""Show columns"""

print(df.columns)

"""Dataset Info"""

print(df.info())

"""Check Missing Values"""

print(df.isnull().sum())

"""Remove Duplicates"""

df.drop_duplicates(inplace=True)

"""Convert Date Column"""

print(df.columns)

df['Order Date'] = pd.to_datetime(df['Order Date'], dayfirst=True)

"""Basic Statistics"""

print("\nTotal Sales:", df['Sales'].sum())
print("Average Sales:", df['Sales'].mean())
print("Maximum Sales:", df['Sales'].max())
print("Minimum Sales:", df['Sales'].min())

"""Daily Sales Trend"""

daily_sales = df.groupby('Order Date')['Sales'].sum()

plt.figure(figsize=(10,5))
plt.plot(daily_sales)
plt.title("Daily Sales Trend")
plt.xlabel("Date")
plt.ylabel("Sales")
plt.show()

"""Monthly Sales Trend"""

df['Month'] = df['Order Date'].dt.month

monthly_sales = df.groupby('Month')['Sales'].sum()

plt.figure(figsize=(8,5))
monthly_sales.plot(kind='bar')
plt.title("Monthly Sales")
plt.xlabel("Month")
plt.ylabel("Sales")
plt.show()

"""Region-wise Sales"""

store_sales = df.groupby('Region')['Sales'].sum()

plt.figure(figsize=(8,5))
store_sales.plot(kind='bar')
plt.title("Region-wise Sales")
plt.xlabel("Region")
plt.ylabel("Sales")
plt.show()

"""Product-wise Sales"""

item_sales = df.groupby('Product Name')['Sales'].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(10,5))
item_sales.plot(kind='bar')
plt.title("Top Selling Products")
plt.xlabel("Product Name")
plt.ylabel("Sales")
plt.show()

"""Sales Distribution"""

plt.figure(figsize=(8,5))
sns.histplot(df['Sales'], bins=20, kde=True)
plt.title("Sales Distribution")
plt.show()

"""Boxplot for Outlier Detection"""

plt.figure(figsize=(8,5))
sns.boxplot(x=df['Sales'])
plt.title("Sales Outliers")
plt.show()

"""Correlation Heatmap"""

numeric_df = df.select_dtypes(include=['int64', 'float64'])

plt.figure(figsize=(6,4))
sns.heatmap(numeric_df.corr(), annot=True, cmap='coolwarm')
plt.title("Correlation Heatmap")
plt.show()

"""Insights"""

print("\nEDA Completed Successfully")
print("Sales trends, store performance, and product analysis generated.")
print("This analysis helps support future sales forecasting.")